import type { TranslationKey } from '@navet/app/i18n';
import type { AvailableSensor, SensorGroupColorConfig } from './types';

export type AvailableSensorDefinition = Omit<AvailableSensor, 'label'> & {
  labelKey: TranslationKey;
  valueKey?: TranslationKey;
};

export const AVAILABLE_SENSOR_DEFINITIONS: AvailableSensorDefinition[] = [
  {
    id: 'energy-today',
    labelKey: 'energy.model.today',
    value: '12.4',
    unit: 'kWh',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-current',
    labelKey: 'climate.current',
    value: '2.3',
    unit: 'kW',
    icon: 'activity',
    category: 'energy',
  },
  {
    id: 'energy-bathroom',
    labelKey: 'sensorGroup.sample.bathroom',
    value: '450',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-kitchen',
    labelKey: 'sensorGroup.sample.kitchen',
    value: '1.2',
    unit: 'kW',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-bedroom',
    labelKey: 'sensorGroup.sample.bedroom',
    value: '320',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-living',
    labelKey: 'sensorGroup.sample.livingRoom',
    value: '890',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-week',
    labelKey: 'calendar.settings.thisWeek',
    value: '84.2',
    unit: 'kWh',
    icon: 'trend-up',
    category: 'energy',
  },
  {
    id: 'energy-month',
    labelKey: 'calendar.settings.thisMonth',
    value: '342',
    unit: 'kWh',
    icon: 'trend-up',
    category: 'energy',
  },
  {
    id: 'temp-indoor',
    labelKey: 'climate.temperature',
    value: '21',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-indoor',
    labelKey: 'weather.humidity',
    value: '55',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'temp-outdoor',
    labelKey: 'sensorGroup.sample.outdoorTemperature',
    value: '18',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-outdoor',
    labelKey: 'sensorGroup.sample.outdoorHumidity',
    value: '72',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'temp-bedroom',
    labelKey: 'sensorGroup.sample.bedroomTemperature',
    value: '19',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-bedroom',
    labelKey: 'sensorGroup.sample.bedroomHumidity',
    value: '48',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'air-quality',
    labelKey: 'sections.climate.airQuality.title',
    value: 'Good',
    valueKey: 'charts.quality.goodLabel',
    unit: '',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'wind-speed',
    labelKey: 'weather.metric.wind',
    value: '12',
    unit: 'km/h',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'uv-index',
    labelKey: 'weather.metric.uvIndex',
    value: '5',
    unit: '',
    icon: 'sun',
    category: 'environmental',
  },
  {
    id: 'pressure',
    labelKey: 'weather.metric.pressure',
    value: '1013',
    unit: 'hPa',
    icon: 'gauge',
    category: 'environmental',
  },
  {
    id: 'co2',
    labelKey: 'sensorGroup.sample.co2Level',
    value: '420',
    unit: 'ppm',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'noise-level',
    labelKey: 'sensorGroup.sample.noiseLevel',
    value: '42',
    unit: 'dB',
    icon: 'activity',
    category: 'other',
  },
  {
    id: 'light-level',
    labelKey: 'sensorGroup.sample.lightLevel',
    value: '450',
    unit: 'lux',
    icon: 'sun',
    category: 'other',
  },
];

export const SENSOR_GROUP_COLOR_MAP: Record<
  'teal' | 'blue' | 'purple' | 'amber' | 'emerald',
  SensorGroupColorConfig
> = {
  teal: {
    iconBg: 'bg-teal-500/20',
    iconColor: 'text-teal-400',
    hover: 'hover:bg-teal-500/10',
    selected: 'bg-teal-500/20 border-teal-500/40',
  },
  blue: {
    iconBg: 'bg-blue-500/20',
    iconColor: 'text-blue-400',
    hover: 'hover:bg-blue-500/10',
    selected: 'bg-blue-500/20 border-blue-500/40',
  },
  purple: {
    iconBg: 'bg-purple-500/20',
    iconColor: 'text-purple-400',
    hover: 'hover:bg-purple-500/10',
    selected: 'bg-purple-500/20 border-purple-500/40',
  },
  amber: {
    iconBg: 'bg-amber-500/20',
    iconColor: 'text-amber-400',
    hover: 'hover:bg-amber-500/10',
    selected: 'bg-amber-500/20 border-amber-500/40',
  },
  emerald: {
    iconBg: 'bg-emerald-500/20',
    iconColor: 'text-emerald-400',
    hover: 'hover:bg-emerald-500/10',
    selected: 'bg-emerald-500/20 border-emerald-500/40',
  },
};
