export type SemanticRole = string;

export const HOME_OS_ROLES = {
  familyPerson: 'family.person',
  familyTracker: 'family.tracker',
  lightingLight: 'lighting.light',
  lightingSwitch: 'lighting.switch',
  deviceSwitch: 'device.switch',
  environmentTemperature: 'environment.temperature',
  environmentHumidity: 'environment.humidity',
  environmentAirQuality: 'environment.air_quality.aqi',
  environmentPm25: 'environment.air_quality.pm25',
  environmentCo2: 'environment.air_quality.co2',
  securityDoor: 'security.door',
  securityWindow: 'security.window',
  securityLock: 'security.lock',
  securityWaterLeak: 'security.water_leak',
  securitySmoke: 'security.smoke',
  diagnosticBattery: 'diagnostic.battery',
  diagnosticConnectivity: 'diagnostic.connectivity',
  homelabPveOnline: 'homelab.pve.online',
  homelabPveCpu: 'homelab.pve.cpu',
  homelabPveTemperature: 'homelab.pve.temperature',
  homelabPveMemory: 'homelab.pve.memory',
  homelabHomeAssistantOnline: 'homelab.home_assistant.online',
  homelabHomeAssistantVersion: 'homelab.home_assistant.version',
  homelabHomeAssistantCpu: 'homelab.home_assistant.cpu',
  homelabHomeAssistantMemory: 'homelab.home_assistant.memory',
  energyElectricityToday: 'energy.electricity.today',
  energyElectricityMonth: 'energy.electricity.month',
  energyElectricityBalance: 'energy.electricity.balance',
  energyGasCurrent: 'energy.gas.current',
  networkRouterOnline: 'network.router.online',
  networkRouterUptime: 'network.router.uptime',
  networkRouterClients: 'network.router.clients',
  networkInternetOnline: 'network.internet.online',
  networkInternetLatency: 'network.internet.latency',
  networkInternetPacketLoss: 'network.internet.packet_loss',
  weatherCurrent: 'weather.current',
  familyCalendar: 'family.calendar',
  homeMode: 'home.mode',
  homeCleaning: 'home.cleaning',
} as const satisfies Record<string, SemanticRole>;
