export type SemanticRole = string;

export const HOME_OS_ROLES = {
  familyPerson: 'family.person',
  familyTracker: 'family.tracker',
  lightingLight: 'lighting.light',
  lightingSwitch: 'lighting.switch',
  deviceSwitch: 'device.switch',
  environmentTemperature: 'environment.temperature',
  environmentHumidity: 'environment.humidity',
  securityDoor: 'security.door',
  securityWindow: 'security.window',
  securityLock: 'security.lock',
  securityWaterLeak: 'security.water_leak',
  securitySmoke: 'security.smoke',
  diagnosticBattery: 'diagnostic.battery',
  diagnosticConnectivity: 'diagnostic.connectivity',
  homelabPveOnline: 'homelab.pve.online',
  homelabPveCpu: 'homelab.pve.cpu',
  homelabPveTemperature: 'homelab.pve.temperature',
  homelabPveMemory: 'homelab.pve.memory',
  energyElectricityToday: 'energy.electricity.today',
  energyElectricityMonth: 'energy.electricity.month',
  energyElectricityBalance: 'energy.electricity.balance',
  energyGasCurrent: 'energy.gas.current',
  networkRouterOnline: 'network.router.online',
  networkInternetLatency: 'network.internet.latency',
  networkInternetPacketLoss: 'network.internet.packet_loss',
} as const satisfies Record<string, SemanticRole>;
