export const STORAGE_KEYS = {
  cardSizes: 'navet-card-sizes',
  mediaSectionCardSizes: 'navet-media-section-card-sizes',
  mediaDefaultViews: 'navet-media-default-views',
  mediaBrowserExpandedViews: 'navet-media-browser-expanded-views',
  mediaNowPlayingSession: 'navet-media-now-playing-session',
  mediaCollapsedSections: 'navet-media-collapsed-sections',
  cardOrders: 'navet-card-orders',
  roomOrder: 'navet-room-order',
  hiddenRooms: 'navet-hidden-rooms',
  roomOrganization: 'navet-room-organization',
  roomWorkspace: 'navet-room-workspace-v2',
  allViewGrouping: 'navet-all-view-grouping',
  switchCardMetricPreferences: 'navet-switch-card-metrics',
  switchCardIcons: 'navet-switch-card-icons',
  switchCardTintColors: 'navet-switch-card-tint-colors',
  sensorCardIcons: 'navet-sensor-card-icons',
  calendarCardSources: 'navet-calendar-card-sources',
  calendarCardViewModes: 'navet-calendar-card-view-modes',
  calendarCardTintColors: 'navet-calendar-card-tint-colors',
  weatherCardTintColors: 'navet-weather-card-tint-colors',
  energySparklineCardSizes: 'navet-energy-sparkline-card-sizes',
  energyHiddenConsumerIds: 'navet-energy-hidden-consumer-ids',
  energyOverviewLayout: 'navet-energy-overview-layout-v1',
  energyKpiPreferences: 'navet-energy-kpi-preferences-v1',
  securityOverviewPreferences: 'navet-security-overview-preferences-v1',
  rssFeedProviders: 'navet-rss-feed-providers',
  rssCardProviders: 'navet-rss-card-providers',
  rssCardArticleCount: 'navet-rss-card-article-count',
  lightMemoryState: 'navet-light-memory-state',
  cardZones: 'navet-card-zones',
  homeDashboardLayout: 'navet-home-layout',
  dashboardCollection: 'navet-dashboard-collection',
  dashboardProfileSync: 'navet-dashboard-profile-sync',
  dashboardPreferenceSync: 'navet-dashboard-preference-sync',
  dashboardProfileBase: 'navet-dashboard-profile-base',
  dashboardClientIdentity: 'navet-dashboard-client-identity',
  settingsProfileScopes: 'navet-settings-profile-scopes',
} as const;

export const LEGACY_STORAGE_KEYS = {
  cardSizes: 'ha-dashboard-card-sizes',
  mediaSectionCardSizes: 'ha-dashboard-media-section-card-sizes',
  mediaDefaultViews: 'ha-dashboard-media-default-views',
  mediaBrowserExpandedViews: 'ha-dashboard-media-browser-expanded-views',
  mediaNowPlayingSession: 'ha-dashboard-media-now-playing-session',
  mediaCollapsedSections: 'ha-dashboard-media-collapsed-sections',
  cardOrders: 'ha-dashboard-card-orders',
  roomOrder: 'ha-dashboard-room-order',
  hiddenRooms: 'ha-dashboard-hidden-rooms',
  roomOrganization: 'ha-dashboard-room-organization',
  roomWorkspace: 'ha-dashboard-room-workspace-v2',
  allViewGrouping: 'ha-dashboard-all-view-grouping',
  switchCardMetricPreferences: 'ha-dashboard-switch-card-metrics',
  switchCardIcons: 'ha-dashboard-switch-card-icons',
  switchCardTintColors: 'ha-dashboard-switch-card-tint-colors',
  sensorCardIcons: 'ha-dashboard-sensor-card-icons',
  calendarCardSources: 'ha-dashboard-calendar-card-sources',
  calendarCardViewModes: 'ha-dashboard-calendar-card-view-modes',
  calendarCardTintColors: 'ha-dashboard-calendar-card-tint-colors',
  weatherCardTintColors: 'ha-dashboard-weather-card-tint-colors',
  energySparklineCardSizes: 'ha-dashboard-energy-sparkline-card-sizes',
  energyHiddenConsumerIds: 'ha-dashboard-energy-hidden-consumer-ids',
  rssFeedProviders: 'ha-dashboard-rss-feed-providers',
  rssCardProviders: 'ha-dashboard-rss-card-providers',
  rssCardArticleCount: 'ha-dashboard-rss-card-article-count',
  lightMemoryState: 'ha-dashboard-light-memory-state',
  cardZones: 'ha-dashboard-card-zones',
  homeDashboardLayout: 'ha-dashboard-home-layout',
  settingsProfileScopes: 'ha-dashboard-settings-profile-scopes',
} as const;

export const STORE_STORAGE_KEYS = {
  settings: 'navet-settings',
  theme: 'navet-theme',
  navigation: 'navet-navigation',
  editMode: 'navet-edit-mode',
  customCards: 'navet-custom-cards',
  entityRoomOverrides: 'navet-entity-room-overrides',
  lightPresetSettings: 'navet-light-preset-settings',
} as const;

export const LEGACY_STORE_STORAGE_KEYS = {
  settings: 'ha-dashboard-settings',
  theme: 'ha-dashboard-theme',
  navigation: 'ha-dashboard-navigation',
  editMode: 'ha-dashboard-edit-mode',
  customCards: 'ha-dashboard-custom-cards',
  entityRoomOverrides: 'ha-dashboard-entity-room-overrides',
  lightPresetSettings: 'ha-dashboard-light-preset-settings',
} as const;
