location ^~ /__navet_auth__/ {
  include /etc/nginx/snippets/navet-security-headers.conf;
  client_max_body_size 24k;
  access_log off;
  add_header Cache-Control "no-store" always;
  js_content navet_auth_store.handle;
}
