location = /__navet_openhab__/session {
  include /etc/nginx/snippets/navet-security-headers.conf;
  client_max_body_size 12k;
  access_log off;
  add_header Cache-Control "no-store" always;
  js_content navet_openhab_store.handle;
}
