location /__navet_homey__/ {
  include /etc/nginx/snippets/navet-security-headers.conf;
  client_max_body_size 16k;
  access_log off;
  add_header Cache-Control "no-store" always;
  js_content navet_homey_store.handle;
}
